GAME_TO_FILENAME_MAP = {
    "18 Wheeler\nStandard": "18_Wheeler_STD.bin",
    "Mystery Game!\n402.bin": "402.bin",
    "Akatsuki Blitz\nkampf Ausf Achse": "Akatsuki_Bk_Ausf_Achse.bin",
    "Alienfront": "AlienFront.bin",
    "Azumanga Daioh\nPuzzle Bobble": "AzumangaDaiohPuzzleBobble_v3.bin",
    "Beach Spikers": "BeachSpikers.bin",
    "Border Down": "BorderDown_v3.bin",
    "Burning Casino": "BurningCasino_v3.bin",
    "Capcom Vs. SNK 2": "Capcom_Vs_SNK_2_Millionaire_Fighting_2001.bin",
    "Chaos Field": "ChaosField_v3.bin",
    "Cleopatra\nFortune Plus": "CleopatraFortunePlus_v6.bin",
    "Club Kart\nEuropean Session": "ClubKartEuropeanSessionUnlocked.bin",
    "Cosmic Smash": "CosmicSmash.bin",
    "Crazy Taxi" : "CrazyTaxi.bin",
    "Mystery Game!\ncvspro.bin": "cvspro.bin",
    "Dead Or Alive 2\nMillenium": "DeadOrAlive2Millenium.bin",
    "Death Crimson OX": "DeathCrimsonOX.bin",
    "Doki Doki Idol\nStar Seeker": "DokiDokiIdolStarSeeker.bin",
    "Dolphin Blue": "dolphinblue.bin",
    "Dynamite Deka EX": "DynamiteDekaEx.bin",
    "Hokuto No Ken": "FOTNS_Naomi2_Fixed.bin",
    "Animal Basket": "gdrom_anmlbskt.bin",
    "King Of Fighters\nXI": "gdrom_KOFXI_v5.bin",
    "Rumble Fish 2": "gdrom_rumblef2_v4.bin",
    "Guilty Gear\nIsuka": "ggisuka.bin",
    "Giant Gram 2000": "Giant_Gram_2000.BIN",
    "Giga Wing 2": "GigaWing2.bin",
    "Guilty Gear XX\nAccent Core": "GuiltyGearXXAccentCore_v6.bin",
    "Guilty Gear XX\nSlash": "GuiltyGearXXSlash_v6.bin",
    "Cannon Spike": "GunSpike.bin",
    "Heavy Metal:\nGeomatrix": "HeavyMetalGeomatrix.bin",
    "Ikaruga": "Ikaruga_v3.bin",
    "Illvelo": "Illvelo_v6.bin",
    "Initial D 2\nExport": "InitialD2exp.bin",
    "Initial D 3\nExport": "InitialD3Export.Bin",
    "Initial D\nExport": "InitialDexp.bin",
    "Jumbo! Safari": "Jambo_Safari.bin",
    "Jingi Storm:\nThe Arcade": "JingyStormTheArcade.bin",
    "Karous": "karous_v3.bin",
    "King Of Fighters\nNeo Wave": "KingOfFightersNewWave.bin",
    "King Of Route 66": "KingOfRoute66.bin",
    "Knights Of Valour\nSeven Spirits": "kov7spirits_Naomi2_Fixed.bin",
    "Kuru Kuru\nChameleon": "KuruKuruChameleon_v3.bin",
    "Lupin 3: The\nShooting": "Lupin3-TheShooting.bin",
    "Mamoru-kun wa\nNoro. Shimatta!": "mamonorov6.bin",
    "Marvel Vs.\nCapcom 2": "MarvelVsCapcom2.bin",
    "Melty Blood:\nAct Cadenza (B2)": "MeltyBloodActCadenzaVerB2_v3.bin",
    "Melty Blood\nActress Again": "MeltyBloodActressAgain.bin",
    "Metal Slug 6": "MetalSlug6.bin",
    "Mobile Suit Gundam\nFed Vs. Zeon DX": "MobileSuitGundam-FederationVsZeonDX.bin",
    "Monkey Ball": "MonkeyBall.bin",
    "Musapey No\nChoco Marker": "MusapeysChocoMarker.bin",
    "Noukone Puzzle\nTakoron": "NoukonePuzzleTakoron.bin",
    "Power Stone 2": "PowerStone2.bin",
    "Power Stone": "Powerstone-alt.BIN",
    "Psyvariar 2": "Psyvariar2_v6.bin",
    "Puyo Puyo Fever": "PuyoPuyoFever_v6.bin",
    "Quiz Keitai\nQ Mode": "QuizKeitaiQMode.bin",
    "Radirgy Noa": "RadirgyNoa_v6.bin",
    "Radirgy": "Radirgy_v3.bin",
    "Rival Schools 2:\nProject Justice": "RivalSchools2-ProjectJustice.bin",
    "Samba De Amigo": "Samba_De_Amigo_EPR-22966B_Patched.bin",
    "SEGA\nMarine Fishing": "Sega_Marine_Fishing_EPR-22221.bin",
    "SEGA\nStrike Fighter": "SegaStrikeFighter.bin",
    "SEGA Tetris": "SegaTetris.bin",
    "Senko No Ronde\nNew Version": "senkonewv6.bin",
    "Senko No Ronde\nSP": "SenkoNoRondeSP_v3.bin",
    "Shikigami no\nShiro II": "ShikigamiNoShiroII_v6.bin",
    "Shooting Love\n2007: Exzeal": "ShootingLove2007-Exzeal_v6.bin",
    "Slash Out": "Slashout.bin",
    "Spawn": "spawn.bin",
    "Spikers Battle": "SpikersBattle.bin",
    "Sports Jam": "SportsJam.bin",
    "Street Fighter\nZero 3 Upper": "StreetFighterZero3Upper.bin",
    "Super Shanghai\n2005": "SuperShanghai2005VerA_v6.bin",
    "Tetris\nKiwamemichi": "TetrisKiwamemichi_v6.bin",
    "Toy Fighter": "ToyFighter.bin",
    "Triggerheart\nExelica": "TriggerHeartExelica_v6.bin",
    "Trizeal": "Trizeal_v3.bin",
    "Under Defeat": "UnderDefeat_v3.bin",
    "Virtua Athlete": "VirtuaAthlete.bin",
    "Virtua Figter 4\nFinal Tuned": "VirtuaFighter4FinalTuned_verb.bin",
    "Virtua Golf": "VirtuaGolf.bin",
    "Virtua NBA": "VirtuaNBA.bin",
    "Virtua Striker 2\nVer.2000": "VirtuaStriker2-2000.bin",
    "Virtua Striker 3": "VirtuaStriker3.bin",
    "Virtua Tennis 2": "VirtuaTennis2.bin",
    "Virtua Tennis": "VirtuaTennis.bin",
    "Wave Runner GP": "WaveRunnerGP.bin",
    "World Series\nBaseball": "WorldSeriesBaseball.bin",
    "WWF Royal Rumble": "WWF_Royal_Rumble.BIN",
    "Zero Gunner 2": "ZeroGunner2.bin",
    "Zombie Revenge": "ZombieRevenge.bin"
}
